
@host = http://localhost:5000
@contentType = application/json
@username = nick
@productId = 623c07fb21b32d4bb4b8a11e

###
GET {{host}}/users HTTP/1.1

###
GET {{host}}/users/{{username}} HTTP/1.1

###
GET {{host}}/users/{{username}}/details HTTP/1.1

###
GET {{host}}/products HTTP/1.1

###

GET {{host}}/products/{{productId}} HTTP/1.1

###
POST {{host}}/purchase/{{username}}/{{productId}} HTTP/1.1
Content-Type: {{contentType}}

{
  "quantity": 5000
}